site_name: "Aaron Braundmeier"
site_url: https://www.braundmeier.com
site_description: "Aaron Braundmeier's personal portfolio"
site_author: "Aaron Braundmeier"
nav:
  - About Me: index.md
  - Certificates: certs.md
  - Contact: contact.md
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  custom_dir: overrides
  icon:
    logo: material/ab-testing
  favicon: favicon.svg
  font:
    text: Ubuntu
    code: Fira Code
  features:
    - palette.toggle
    - navigation.tabs
    - content.tooltips
    - content.code.copy
    - content.code.select
extra_css:
  - /stylesheets/extra.css
  - /assets/fonts/fonts.css
extra:
  generator: false
  analytics:
    provider: google
    property: "G-WF0BEBS62L"
markdown_extensions:
  - admonition
  - abbr
  - def_list
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
plugins:
  - mermaid2
  - search
extra_javascript:
  - javascripts/extra.js
  - ./javascripts/extra.js
  - ./javascripts/adsense.js
