site_name: GraphQL Guide
site_url: https://www.k8s.guide
site_description: "A comprehensive, easy-to-follow guide for GraphQL"
site_author: "Aaron Braundmeier"
nav:
  - Home: index.md
  - Introduction: apollo_graphql_introduction.md
  - Core Concepts: apollo_graphql_core_concepts.md
  - Server Setup: apollo_server_setup_configuration.md
  - Client Setup: apollo_client_setup_configuration.md
  - Real-time Data: apollo_subscriptions_real_time_data.md
  - Federation: apollo_federation_schema_stitching.md
  - Client Caching: apollo_client_caching_state_management.md
  - Error Handling: apollo_error_handling_debugging.md
  - Security & Auth: apollo_security_authentication.md
  - Performance: apollo_performance_optimization.md
  - Best Practices: apollo_best_practices.md
  - About Me: about.md
theme:
  name: material
  custom_dir: overrides
  logo: logo.png
  favicon: favicon.svg
  font:
    text: Ubuntu
    code: Fira Code
  features:
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.sections
    - palette.toggle
    - content.tooltips
    - content.code.copy
    - content.code.select
extra_css:
  - /stylesheets/extra.css
extra:
  generator: false
  analytics:
    provider: google
    property: "G-WF0BEBS62L"
markdown_extensions:
  - admonition
  - abbr
  - def_list
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
plugins:
  - mermaid2
  - search
  - inline-svg
extra_javascript:
  - ./javascripts/extra.js
  - ./javascripts/adsense.js
